# Generated by Django 5.2.4 on 2025-07-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
