# Generated by Django 5.2.4 on 2025-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customusermodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customusermodel",
            options={"verbose_name": "회원", "verbose_name_plural": "회원목록"},
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="username",
            field=models.CharField(
                help_text="150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                verbose_name="-",
            ),
        ),
    ]
