# Generated by Django 5.2.4 on 2025-07-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customusermodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "이미 가입된 이메일 주소입니다."},
                help_text="* 필수 기재 항목입니다.",
                max_length=255,
                unique=True,
                verbose_name="이메일",
            ),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="name",
            field=models.CharField(
                help_text="* 필수 기재 항목입니다.",
                max_length=50,
                verbose_name="사용자 이름",
            ),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="nickname",
            field=models.CharField(
                error_messages={"unique": "중복이 불가능합니다."},
                help_text="* 필수 기재 항목입니다.",
                max_length=50,
                unique=True,
                verbose_name="닉네임",
            ),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="username",
            field=models.CharField(verbose_name="이름"),
        ),
    ]
