version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/oz
hooks:
  AfterInstall:
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: oz/run.sh
      timeout: 300
      runas: root
