# Generated by Django 5.2.4 on 2025-07-22 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_account_options_alter_account_account_number_and_more",
        ),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="거래 금액"
                    ),
                ),
                (
                    "balance_after_transaction",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="거래 후 잔액"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="거래 내역"
                    ),
                ),
                (
                    "io_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")],
                        max_length=10,
                        verbose_name="입출금 타입",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ATM", "ATM 거래"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTOMATIC_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                            ("INTEREST", "이자"),
                        ],
                        max_length=20,
                        verbose_name="거래 타입",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="거래 일시"),
                ),
                (
                    "transaction_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="거래 내역 수정 일시"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.account",
                        verbose_name="계좌 정보",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 내역",
                "verbose_name_plural": "거래 내역들",
            },
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
