# Generated by Django 5.2.4 on 2025-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "balance_after_transaction",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "io_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")],
                        max_length=10,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ATM", "ATM 거래"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTOMATIC_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                            ("INTEREST", "이자"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
