# Generated by Django 5.2.4 on 2025-07-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customusermodel_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customusermodel",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자들"},
        ),
        migrations.AlterModelManagers(
            name="customusermodel",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "이미 가입된 이메일 주소입니다."},
                help_text="이메일 형식을 준수해주세요.",
                max_length=255,
                unique=True,
                verbose_name="이메일",
            ),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="스태프 여부"),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="계정 활성화 여부"),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="전화번호"
            ),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="최근 업데이트 일시"
            ),
        ),
    ]
